---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: imgctrl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imgctrl
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - watch
  - get
  - list
- apiGroups: 
  - ""
  resources: 
  - configmaps
  verbs:
  - watch
  - get
  - list
  - create
  - update
- apiGroups:
  - shipwright.io
  resources:
  - images
  - images/status
  - imageimports
  - imageimports/status
  verbs:
  - "*"
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imgctrl
subjects:
- kind: ServiceAccount
  name: imgctrl
  namespace:  '{{repl Namespace }}'
roleRef:
  kind: ClusterRole
  name: imgctrl
  apiGroup: rbac.authorization.k8s.io
