---
apiVersion: v1
kind: Service
metadata:
  name: validating-webhook
spec:
  selector:
    app: imgctrl
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: imageio
spec:
  selector:
    app: imgctrl
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: metrics
spec:
  selector:
    app: imgctrl
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: imageio-external
spec:
  type: NodePort
  selector:
    app: imgctrl
  ports:
    - port: 8083
      nodePort: 8083
