apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: imgctrl
  namespace: monitoring
  labels:
    app: imgctrl
spec:
  namespaceSelector:
    matchNames:
      - '{{repl Namespace }}'
  selector:
    matchLabels:
      app: imgctrl
  endpoints:
    - port: metrics
      interval: 5s
      path: /
