apiVersion: v1
kind: Secret
metadata:
  name: certs
type: Opaque
data:
  tls.key: |
    {{repl ConfigOption "tls_private_key_file" | indent 4}}
  tls.crt: |
    {{repl ConfigOption "tls_public_key_file"  | indent 4}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: imgctrl
webhooks:
- name: image.shipwright.io
  rules:
  - apiGroups:
    - shipwright.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - images
    scope: Namespaced
  clientConfig:
    service:
      namespace: '{{repl Namespace }}'
      name: validating-webhook
      path: "/image"
      port: 8080
    caBundle: |
      {{repl ConfigOption "tls_public_key_file" | indent 6 }}
  admissionReviewVersions:
  - v1
  sideEffects: None
  timeoutSeconds: 3
- name: imageimport.shipwright.io
  rules:
  - apiGroups:
    - shipwright.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - imageimports
    scope: Namespaced
  clientConfig:
    service:
      namespace: '{{repl Namespace }}'
      name: validating-webhook
      path: "/imageimport"
      port: 8080
    caBundle: |
      {{repl ConfigOption "tls_public_key_file" | indent 6 }}
  admissionReviewVersions:
  - v1
  sideEffects: None
  timeoutSeconds: 3
